version: 2.1
executors:
  python-executor:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest tests/*.py
  scrape:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: scrape
          command: |
            . venv/bin/activate
            python main.py
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "40 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - scrape
