version: 2.1
executors:
  python-executor:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python -m unittest tests/*.py
  scrape:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: scrape
          command: python main.py
workflows:
  version: 2
  commit:
    jobs:
      - build
      - scrape:
          requires:
            - build
  nightly:
    triggers:
      - schedule:
          cron: "36 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - scrape