version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest tests/*.py
  scrape:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          name: scrape
          command: |
            . venv/bin/activate
            python main.py
workflows:
  version: 2
  commit:
    jobs:
      - build
      - scrape:
          requires:
            - build
  nightly:
    triggers:
      - schedule:
          cron: "30 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - scrape:
          requires:
            - build
