robinho:
  working_directory: ~/project
  docker:
    - image: circleci/python:3.6.4
  steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          pip install -r requirements.txt
    - run:
        name: run tests
        command: |
          python -m unittest tests/*.py
    - run:
        name: scrape
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            python main.py
          fi
